disquaire-project/disquaire/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from store import views

urlpatterns = [
    path('', views.index, name='index'),
    path('store/', include('store.urls', namespace='store')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

disquaire-project/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.listing, name='listing'),
    path('<int:album_id>', views.detail, name='detail'),
    path('search/', views.search, name='search')
]

disquaire-project/store/models.py
from django.db import models


class Artist(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)

    def __str__(self):
        return self.name


class Album(models.Model):
    reference = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    image = models.ImageField(default='default.jpg', upload_to='album_pics')
    artists = models.ManyToManyField(Artist, related_name='albums', blank=True)

    def __str__(self):
        return self.title


class Booking(models.Model):
    contacted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    album = models.OneToOneField(Album, on_delete=models.CASCADE)

    def __str__(self):
        return self.contact.name

disquaire-project/store/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Album, Artist, Booking, Contact


def index(request):
    albums = Album.objects.filter(available=True).order_by('-created_at')[:10]
    context = {
        'albums': albums
    }
    return render(request, 'store/index.html', context)


def listing(request):
    albums = Album.objects.filter(available=True)
    context = {
        'albums': albums
    }
    return render(request, 'store/listing.html', context)


def detail(request, album_id):
    album = Album.objects.get(pk=album_id)
    artists = " ".join([artist.name for artist in album.artists.all()])
    artists_name = "".join(artists)
    context = {
        'album_title': album.title,
        'artists_name': artists_name,
        'album_id': album.id,
        'thumbnail': album.image

    }
    return render(request, 'store/detail.html', context)


def search(request):
    query = request.GET.get('query')
    if not query:
        albums = Album.objects.all()
    else:
        albums = Album.objects.filter(title__icontains=query)

        if not albums.exists():
            albums = Album.objects.filter(artists__name__icontains=query)

    title = "Résultats pour la requête %s" % query
    context = {
        'albums': albums,
        'title': title
    }

    return render(request, 'store/search.html', context)

disquaire-project/store/templates/store/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'store/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/business-casual.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="brand"><a href="/">Le bateau pirate</a></div>
    <div class="address-bar">Radio rock, Mer du nord (ou dans le 20e, à Paris)</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Le bateau pirate</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'store:listing' %}">Tous nos disques</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <div class="container">
      <div class="row">
        <div class="box">
            {% block content %}     {% endblock %}
        </div>
      </div>
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="#" target="_blank">Azzeddine Dali</a> &reg; Made With Love </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'store/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>

  </body>
</html>

disquaire-project/store/templates/store/detail.html
{% extends 'store/base.html' %}

{% block content %}
<hr>
<h1 class="intro-text text-center">{{ album_title }}</h1>
<hr class="detail-separator">
<div class="col-md-6">
  <img src="{{ thumbnail.url }}" alt="{{ album_title }}" class="img-responsive">
</div>
<div class="col-md-6">
  <div style="margin-bottom:45px">
    <h2 class="text-center artist_name">Artistes</h2>
    <p>{{ artists_name }}</p>
  </div>

  <h2 class="text-center artist_name">Réserver {{ album_title }}</h2>
  <p style="margin-bottom: 20px;">Demandez-nous de mettre de côté {{ album_title }} et venez le chercher dès demain en magasin ! </p>
  <form class="form-inline" action="/" method="post">

    <div class="form-group">
      <label for="name" class="control-label">Nom</label>
      <input type="text" name="name" value="" id="name">
    </div>
    <div class="form-group">
      <label for="email" class="control-label">E-mail</label>
      <input type="text" name="email" value="" id="email">
    </div>
    <!-- <input type="hidden" class="hidden" value="" name="album_id"> -->

    <button type="submit" class="btn btn-success">Réserver</button>
  </form>

</div>


{% endblock %}

disquaire-project/store/templates/store/index.html
{% extends 'store/base.html' %}

{% block content %}

    {% include 'store/list.html' with list_title='Nos derniers disques' %}

{% endblock %}

disquaire-project/store/templates/store/list.html
<div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">{{ list_title }}
    </h2>
    <hr class="detail-separator">
</div>

{% if albums|length_is:"0" %}

    <div class="text-center">
      Palsambleu ! Nous n'avons trouvé aucun résultat à cette requête. Même pas de quoi se ronger la chique !
      Partez de nouveau à l'abordage !
    </div>

{% else %}

    {% for album in albums %}
        <div class="col-sm-4 text-center">
            <a href="{% url 'store:detail' album_id=album.id  %}">
              <img class="img-responsive" src="{{ album.image.url }}" alt="{{ album.title }}">
            </a>
            <h3><a href="{% url 'store:detail' album_id=album.id  %}">{{ album.title }}</a></h3>
            {% for artist in album.artists.all %}
                <p>{{ artist.name }}</p>
            {% endfor %}
        </div>
        {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
    {% endfor %}

{% endif %}

disquaire-project/store/templates/store/listing.html
{% extends 'store/base.html' %}

{% block content %}

    {% include 'store/list.html' with list_title='Tous nos disques' %}

{% endblock %}

disquaire-project/store/templates/store/search.html
{% extends 'store/base.html' %}

{% block content %}

    {% include 'store/list.html' with list_title=title %}

{% endblock %}